In [1]:
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import scipy.stats as stats
import warnings
warnings.simplefilter("ignore")


In [1]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier
from sklearn import set_config
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RepeatedStratifiedKFold
import xgboost as xgboost
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV



In [3]:
df=pd.read_csv('Iris.csv')

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
lbe_encode=preprocessing.LabelEncoder()
df['Species_encode']=lbe_encode.fit_transform(df['Species'])
df["Species_encode"].value_counts()


0    50
1    50
2    50
Name: Species_encode, dtype: int64

In [6]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  Species_encode  
0       Iris-setosa               0  
1       Iris-setosa               0  
2       Iris-setosa               0  
3       Iris-setosa               0  
4       Iris-setosa               0  
..              ...             ...  
145  Iris-virginica               2  
146  Iris-virginica               2  
147  Iris-virginica               2  
148  Iris-virginica               2  
149  Iris-virginica               2  

[150 rows x 7 columns]

In [7]:
df=df.drop(columns=['Species'])

In [8]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

     Species_encode  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 6 columns]

In [15]:
df.isnull().sum()

Id                0
SepalLengthCm     0
SepalWidthCm      0
PetalLengthCm     0
PetalWidthCm      0
Species_encode    0
dtype: int64

In [16]:
X=df.drop(columns=['Species_encode'])
y=df['Species_encode']

In [30]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [31]:
rf=RandomForestClassifier(n_estimators=100,
    
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features='sqrt',
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    bootstrap=True,
    oob_score=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
    warm_start=False,
    class_weight=None,
    ccp_alpha=0.0,
    max_samples=None,)

In [32]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [33]:
y_pred=rf.predict(X_test)

In [40]:
cv=RepeatedStratifiedKFold( n_splits=10, n_repeats=5)
cross_val_score(rf,X_train,y_train,cv=cv,scoring='accuracy').mean()


from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))



[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [42]:
from sklearn.datasets import load_diabetes

In [45]:
df=pd.read_csv('diabetes.csv')

In [46]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [47]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [49]:
df['Glucose']=np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])
df['Insulin']=np.where(df['Insulin']==0,df['Insulin'].median(),df['Insulin'])
df['SkinThickness']=np.where(df['SkinThickness']==0,df['SkinThickness'].median(),df['SkinThickness'])




In [50]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0             72           35.0     30.5  33.6   
1              1     85.0             66           29.0     30.5  26.6   
2              8    183.0             64           23.0     30.5  23.3   
3              1     89.0             66           23.0     94.0  28.1   
4              0    137.0             40           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0             76           48.0    180.0  32.9   
764            2    122.0             70           27.0     30.5  36.8   
765            5    121.0             72           23.0    112.0  26.2   
766            1    126.0             60           23.0     30.5  30.1   
767            1     93.0             70           31.0     30.5  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [51]:
X=df.drop(columns=['Outcome'])
y=df['Outcome']

In [65]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [66]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
328            2    102.0             86           36.0    120.0  45.5   
118            4     97.0             60           23.0     30.5  28.2   
617            2     68.0             62           13.0     15.0  20.1   
76             7     62.0             78           23.0     30.5  32.6   
408            8    197.0             74           23.0     30.5  25.9   
..           ...      ...            ...            ...      ...   ...   
488            4     99.0             72           17.0     30.5  25.6   
394            4    158.0             78           23.0     30.5  32.9   
205            5    111.0             72           28.0     30.5  23.9   
571            2    130.0             96           23.0     30.5  22.6   
54             7    150.0             66           42.0    342.0  34.7   

     DiabetesPedigreeFunction  Age  
328                     0.127   23  
118                     0.443   22  
617                     0.257   23  
76                      0.391   41  
408                     1.191   39  
..                        ...  ...  
488                     0.294   28  
394                     0.803   31  
205                     0.407   27  
571                     0.268   21  
54                      0.718   42  

[576 rows x 8 columns]

In [ ]:
rf=RandomForestClassifier(n_estimators=300,
    
    criterion='entropy',
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=10,
    min_weight_fraction_leaf=0.0,
    max_features='sqrt',
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    bootstrap=True,
    oob_score=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
    warm_start=False,
    class_weight=None,
    ccp_alpha=0.0,
    max_samples=None,)

In [54]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [55]:
cv=RepeatedStratifiedKFold( n_splits=10, n_repeats=5)
cross_val_score(rf,X_train,y_train,cv=cv,scoring='accuracy').mean()

y_pred=rf.predict(X_test)

from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[112  18]
 [ 22  40]]
0.7916666666666666
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       130
           1       0.69      0.65      0.67        62

    accuracy                           0.79       192
   macro avg       0.76      0.75      0.76       192
weighted avg       0.79      0.79      0.79       192



# manual hyperparameter tuning

In [57]:
rf=RandomForestClassifier(n_estimators=300,
    
    criterion='entropy',
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=10,
    min_weight_fraction_leaf=0.0,
    max_features='sqrt',
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    bootstrap=True,
    oob_score=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
    warm_start=False,
    class_weight=None,
    ccp_alpha=0.0,
    max_samples=None,)

In [58]:
rf.fit(X_train,y_train)
cv=RepeatedStratifiedKFold( n_splits=10, n_repeats=5)
cross_val_score(rf,X_train,y_train,cv=cv,scoring='accuracy').mean()

y_pred=rf.predict(X_test)

from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[120  10]
 [ 30  32]]
0.7916666666666666
              precision    recall  f1-score   support

           0       0.80      0.92      0.86       130
           1       0.76      0.52      0.62        62

    accuracy                           0.79       192
   macro avg       0.78      0.72      0.74       192
weighted avg       0.79      0.79      0.78       192



# Randmisoed search cv

In [75]:
n_estimators=[int(x) for x in np.linspace(200,2000,num=10)]
max_features=['auto','sqrt','log2']
max_depth=[int(x) for x in np.linspace(10,1000,num=10)]
min_samples_split=[2,5,10,14]
min_samples_leaf=[1.,2,4,6,8]

random_grid={
    'n_estimators':n_estimators,
    'max_features':max_features,
    'max_depth':max_depth,
    'min_samples_split':min_samples_split,
    'min_samples_leaf':min_samples_leaf,
    'criterion':['entropy','gini']
}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1.0, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [76]:
rf1=RandomForestClassifier()

rf_randomcv= RandomizedSearchCV(estimator=rf1, param_distributions = random_grid,
                               cv = 3, n_iter = 10, n_jobs=-1)
rf_randomcv.fit(X_train, y_train)

  


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1.0, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]})

In [78]:
rf_randomcv.best_estimator_

RandomForestClassifier(criterion='entropy', max_depth=450, max_features='log2',
                       min_samples_leaf=2, min_samples_split=10,
                       n_estimators=1000)

In [79]:
rf_randomcv.best_params_

{'n_estimators': 1000,
 'min_samples_split': 10,
 'min_samples_leaf': 2,
 'max_features': 'log2',
 'max_depth': 450,
 'criterion': 'entropy'}

In [83]:
best_random_grid=rf_randomcv.best_estimator_

y_pred=best_random_grid.predict(X_test)

from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[107  18]
 [ 27  40]]
0.765625
              precision    recall  f1-score   support

           0       0.80      0.86      0.83       125
           1       0.69      0.60      0.64        67

    accuracy                           0.77       192
   macro avg       0.74      0.73      0.73       192
weighted avg       0.76      0.77      0.76       192



# Gridsearchcv

In [89]:
 from sklearn.model_selection import GridSearchCV
    
param_grid={
    'n_estimators':[rf_randomcv.best_params_['n_estimators']-200,
                    rf_randomcv.best_params_['n_estimators']-100,
                    rf_randomcv.best_params_['n_estimators'],
                    rf_randomcv.best_params_['n_estimators']+100,
                    rf_randomcv.best_params_['n_estimators']+200],
    'max_features':[rf_randomcv.best_params_['max_features']],
    'max_depth':[rf_randomcv.best_params_['max_depth']],
    'min_samples_split':[rf_randomcv.best_params_['min_samples_split']-2,
                         rf_randomcv.best_params_['min_samples_split']-1,
                         rf_randomcv.best_params_['min_samples_split'],
                         rf_randomcv.best_params_['min_samples_split']+2,
                         rf_randomcv.best_params_['min_samples_split']+1],
    'min_samples_leaf':[rf_randomcv.best_params_['min_samples_leaf'],
                        rf_randomcv.best_params_['min_samples_leaf']+2,
                        rf_randomcv.best_params_['min_samples_leaf']+4],
    'criterion':[rf_randomcv.best_params_['criterion']]

}

In [90]:
rf2=RandomForestClassifier()
grid_search=GridSearchCV(estimator=rf2,param_grid=param_grid,
                               cv = 10, verbose=True, n_jobs=-1)
grid_search.fit(X_train, y_train)

Fitting 10 folds for each of 75 candidates, totalling 750 fits


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy'], 'max_depth': [450],
                         'max_features': ['log2'],
                         'min_samples_leaf': [2, 4, 6],
                         'min_samples_split': [8, 9, 10, 12, 11],
                         'n_estimators': [800, 900, 1000, 1100, 1200]},
             verbose=True)

In [91]:
grid_search.best_estimator_

RandomForestClassifier(criterion='entropy', max_depth=450, max_features='log2',
                       min_samples_leaf=4, min_samples_split=9,
                       n_estimators=900)

In [92]:
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 450,
 'max_features': 'log2',
 'min_samples_leaf': 4,
 'min_samples_split': 9,
 'n_estimators': 900}

In [94]:
best_gridsearch=grid_search.best_estimator_


y_pred=best_gridsearch.predict(X_test)

from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[108  17]
 [ 27  40]]
0.7708333333333334
              precision    recall  f1-score   support

           0       0.80      0.86      0.83       125
           1       0.70      0.60      0.65        67

    accuracy                           0.77       192
   macro avg       0.75      0.73      0.74       192
weighted avg       0.77      0.77      0.77       192

